global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: haproxy-stats
    metrics_path: /metrics
    static_configs:
      - targets: ['haproxy:8404']

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']
