global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: haproxy-exporter
    static_configs:
      - targets: ['haproxy-exporter:9101']

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: container-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ['container-metrics:9800']
