server:
  http_listen_port: 12345

logs:
  positions_directory: /tmp/agent-positions
  clients:
    - url: http://loki:3100/loki/api/v1/push
  scrape_configs:
    - job_name: docker-logs
      static_configs:
        - targets:
            - localhost
          labels:
            job: docker
            __path__: /var/lib/docker/containers/*/*.log
    - job_name: astro-logs
      static_configs:
        - targets:
            - localhost
          labels:
            job: astro
            container: astro-blog-astro
            __path__: /var/lib/docker/containers/*astro-blog-astro*/*.log
    - job_name: haproxy-logs
      static_configs:
        - targets:
            - localhost
          labels:
            job: haproxy
            container: astro-blog-haproxy
            __path__: /var/lib/docker/containers/*haproxy*/**/*.log
